### PR TITLE
Drop default of --region

### PR DESCRIPTION
**Pull request by cben**
It was only appropriate for AWS and it's good for users to make a conscious decision before creating clusters.

(This is the last part of addressing https://issues.redhat.com/browse/SDA-3524)

### CODE REVIEW

**Comment by cben** [comment]
2nd commit made some changes to allow the standard `Cmd.MarkFlagRequired("region")`.
Now prints `Error: required flag(s) "region" not set`.

- Moved flag validation & interactive prompts from `RunE` to `PreRunE`.
  This allows interactive helpers to .Set flags that user didn't pass.
  (Cobra enforces required flags between PreRunE & RunE.)

- Fixed interactive helpers to use higher-level `FlagSet.Set()` that
  also marks them `.Changed`.

**Comment by cben** [comment]
@igoihman @nimrodshn please review

**Comment by cben** [comment]
@nimrodshn @vkareh @igoihman @jhernand please review.

**Comment by vkareh** [comment]
Yes, this makes sense

/lgtm

**Comment by cben** [comment]
ping can this be merged?

**Pull request merged**
