### PR TITLE
OCM-6407 | edit option sends an empty payload

### PR DESCRIPTION
**Pull request by ahitacat**
## EDIT
This commit adds a parameter when creating the command that check for a minimum amount of arguments. The
command will fail if no parameters are used.

### CODE REVIEW

**Comment by tzvatot** [comment]
I suggest to use `cmd.Flags().NFlag()` and if it's < 1 then print an INFO message that no change is done.

**Comment by ahitacat** [comment]
I see there is also used in this cli tool the Args check.
```
var Cmd = &cobra.Command{
	...
	Args: cobra.MinimumNArgs(2),
}
```
If I remove the clusterNeedsUpdate bool, I see a possible problem when the --enable-delete-protection parameter is added. As that parameter doesn't require to update the cluster.

**Comment by tzvatot** [comment]
> I see there is also used in this cli tool the [builtin args validator](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#positional-and-custom-arguments).
> 
> ```
> var Cmd = &cobra.Command{
> 	...
> 	Args: cobra.MinimumNArgs(2),
> }
> ```
> 
> If I remove the clusterNeedsUpdate bool, I see a possible problem when the --enable-delete-protection parameter is added. As that parameter doesn't require to update the cluster.

Why not? it requires a patch to the /delete_protection endpoint. It's not the cluster's endpoint, but it's still semantically updating the cluster.

**Comment by mnecas** [comment]
Agree with @ahitacat in case we will use the `--enable-delete-protection` without adding any check to [1] we will still send empty patch request to the `/clusters/{id}` endpoint and patch to update the delete-protection to `/clusters/{id}/delete_protection`. This could lead to unexpected behaviour as we would not update anything in the  `/clusters/{id}`  but still could fail on permission check. 

[1] https://github.com/openshift-online/ocm-cli/blob/109526466d14f5daf8f169cba211e672c0ea4f6e/cmd/ocm/edit/cluster/cmd.go#L271

**Comment by mnecas** [comment]
Ah did not know about the https://github.com/openshift-online/ocm-cli/pull/603 should be good.
lgmt

**Review by tzvatot — APPROVED** [review]
LGTM

**Pull request merged**
