### PR TITLE
cluster describe api listening

### PR DESCRIPTION
**Pull request by dofinn**
Used to quickly determine if a cluster is public or private

### CODE REVIEW

**Comment by dofinn** [comment]
[test]

**Comment by dofinn** [comment]
@vkareh seems like the pr_test.sh is failing to pull packages during CI. Any suggestions ?

**Comment by igoihman** [comment]
@dofinn I fixed the PR check. Please rebase.

**Comment by dofinn** [comment]
Thank you @igoihman

**Pull request merged**
