### PR TITLE
Introduce linting in GH actions

### PR DESCRIPTION
**Pull request by tbrisker**
Also updates linting configuration and fixes new issues.

### CODE REVIEW

**Comment by tbrisker** [comment]
@zvikorn can you PTAL? I think the only meaningful code changes that came from the linting are in areas you touched.

**Comment by jhernand** [comment]
Can we put the lint job inside the `check-pull-request.yaml` file, like we do in the SDK? Just to be consistent across projects.

https://github.com/openshift-online/ocm-sdk-go/blob/e5694fa6c5a1d34fe49299cb670381a3b16422c9/.github/workflows/check-pull-request.yaml#L53-L63

**Comment by tbrisker** [comment]
@jhernand updated, thanks.

**Comment by tbrisker** [comment]
Feel free to squash on merge, the commits were split only for review purposes.

**Comment by zvikorn** [comment]
LGTM

**Pull request merged**
