### PR TITLE
Change oauthURL for RHMI

### PR DESCRIPTION
**Pull request by igoihman**

### CODE REVIEW

**Comment by vkareh** [comment]
This looks good, but it's also missing from the OpenID provider.

**Comment by vkareh** [comment]
Thanks! /lgtm

**Comment by vkareh** [comment]
pipeline is complaining about using `"rhmi"` too many times. One possible solution is to replace the string twice, regardless of product ID:
```go
oauthURL = strings.Replace(consoleURL, "console-openshift-console", "oauth-openshift", 1)
oauthURL = strings.Replace(oauthURL, "solution-explorer", "oauth-openshift", 1)
```
One of them will always be a no-op but it should work. What do you think?

**Comment by igoihman** [comment]
> pipeline is complaining about using `"rhmi"` too many times. One possible solution is to replace the string twice, regardless of product ID:
> 
> ```go
> oauthURL = strings.Replace(consoleURL, "console-openshift-console", "oauth-openshift", 1)
> oauthURL = strings.Replace(oauthURL, "solution-explorer", "oauth-openshift", 1)
> ```
> 
> One of them will always be a no-op but it should work. What do you think?

I can just use a const for rhmi

**Comment by vkareh** [comment]
another nitpick: since you are now importing a common `cluster` pkg, you can now add to it a function `getOauthURL(...)` and reuse it across all three files

**Pull request merged**
